import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EdgeDBProvider } from "@/context/EdgeDBProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-50 text-blue-950`}>
        <EdgeDBProvider>{children}</EdgeDBProvider>
      </body>
    </html>
  );
}

export const preferredRegion = ["cle1"];
